### ISSUE TITLE
Feature: type guarded validation method

### ISSUE THREAD

**Issue by moltar** [marcj/marshal.ts#15]
Would it be possible to add a type guarded validation method?

A method would either return a validated and typed class (or plain object), or throw if invalid.

Usage:

```ts
const res = guard(DataType, data);

// and `res` is now typed
```

**Comment by marcj** [comment]
is `validatedPlainToClass(DataType, data)` what you're looking for? It throws an error or returns the typed version.

**Comment by moltar** [comment]
Yup, and I used that originally, and you refactored it to use a validator, which only returns the error. So that is why I am asking, if there is maybe a better solution?

**Comment by marcj** [comment]
A better solution to what? validatedPlainToClass does what you requested with "guard". What else do you need?
I only refactored to make the benchmark fair.

**Comment by moltar** [comment]
Ok, I will replace the code back with `validatedPlainToClass` then.
