### ISSUE TITLE
TypeError: Cannot add property boolean, object is not extensible

### ISSUE THREAD

**Issue by moltar** [marcj/marshal.ts#16]
When validating a frozen object, that has a missing prop, get the following error:

```
TypeError: Cannot add property boolean, object is not extensible
```

Can see an example here:

https://github.com/moltar/typescript-runtime-type-benchmarks/blob/5990bd77506b6778ba45a4a924ebb8fb83934afe/test/abstract.test.ts#L65

**Comment by marcj** [comment]
I can't replicate that, see https://github.com/marcj/marshal.ts/commit/e0d1a1409ea5a7252dcd0b7986b0194a51fa8af3.

Anything special you're doing in those tests that I'm missing?

**Comment by marcj** [comment]
Works in tests as well now: https://github.com/moltar/typescript-runtime-type-benchmarks/pull/77

**Comment by moltar** [comment]
I think it's something to do with Node versions.

On my local:

```
❯ node -v
v10.15.3
```

And all tests pass.

I think I've seen this before, where older Node versions serialize Error objects differently.

**Comment by moltar** [comment]
Because of that, the error in the snapshot appears generic. But the real error is what I posted in this issue.

**Comment by marcj** [comment]
I see, so since Marshal only supports node 12 I guess we can close this then. Or are you able to reproduce with newer versions as well?

**Comment by moltar** [comment]
Ah, okay, didn't realize it only supports 12. Closing.
