### ISSUE TITLE
Validate doesn't work in Angular 9?

### ISSUE THREAD

**Issue by ericjeker** [marcj/marshal.ts#24]
Hi Marc,

I created a new project using Angular 9 and added the code for validation I found in the documentation. The test fails as no error is returned. I am wondering what am I doing wrong here? Am I missing something?

I understand that this may have something to do with Angular.

Repo with the code: https://github.com/ericjeker/marshal-validation

**Steps:**
```shell
ng new marshal-validation
npm install @marcj/marshal reflect-metadata
# create the page.spec.ts file
ng test
```

**page.spec.ts**
```javascript
import {f, validate, ValidationError} from '@marcj/marshal';

class Page {
    @f
    name: string;

    @f
    age: number;
}

describe('Page', () => {

  it('should fail', () => {

  	const errors = validate(Page, {name: 'peter'});
	expect(errors.length).toBe(1);
	expect(errors[0]).toBeInstanceOf(ValidationError);
	expect(errors[0].path).toBe('age');
	expect(errors[0].message).toBe('Required value is undefined');

  });

  it('should not fail', () => {

  	const errors = validate(Page, {name: 'gabriel', age: 42});
	expect(errors.length).toBe(0);

  });

});
```

**Comment by marcj** [comment]
@ericjeker in your posted repo there is no marshal code. Did you forget to commit it?

**Comment by ericjeker** [comment]
@marcj Holy cow! How can one be so stupid?! :-) Forgot to push actually... Done now.

**Comment by marcj** [comment]
@ericjeker you forgot to set `"emitDecoratorMetadata": true`, which isn't automatically set in Angular 9 as it seems.

**Comment by ericjeker** [comment]
@marcj Oh OK, my bad. I completely missed that point in the documentation. The tests now work properly. Thanks for the help!

Can I suggest to push that "Config" section up right after the "Install" section?

**Comment by marcj** [comment]
@ericjeker Yes, thought the same and already did move it up :)

**Comment by ericjeker** [comment]
Thanks, I will close this ticket.
