### ISSUE TITLE
Issue with IE11/targeting es5

### ISSUE THREAD

**Issue by fusmattia543** [marcj/marshal.ts#25]
When running ng serve on a project using @marcj/marshal, I receive the following error in IE11: 
![image](https://user-images.githubusercontent.com/62338343/77087632-b85ace80-69d9-11ea-9c71-293c955055c6.png)
Which points to:
![image](https://user-images.githubusercontent.com/62338343/77087720-d1fc1600-69d9-11ea-9158-8aefc7a2dc62.png)

I am also targeting es5 in my tsconfig.

**Comment by marcj** [comment]
Yes, Marshal is not built for ES5. If you require ES5 support, you need to transpile it down using Babel.

**Comment by TrevorBroderick1** [comment]
Would transpiling it to ES5 hurt performance much? I am trying to switch off class-transformer to this library (mostly due to poor performance), but without IE11 support this isn't an option unfortunately.

**Comment by marcj** [comment]
Although I've never tested such dated browser, I guess it still works. It's not ES5 that hurts performance, but the IE11 engine itself is slow. You can try and report issues you find. If it's not much work we can tackle them.

**Comment by TrevorBroderick1** [comment]
Thanks for the reply @marcj . I gave it a shot trying to add [babel](https://babeljs.io/docs/en/babel-preset-env) to the project but unfortunately it appears I have no idea what I'm doing.

If you ever get the chance to add ES5 support, it would be really appreciated. I'd love to rip out class-transformer and use this instead.

**Comment by marcj** [comment]
Maybe this helps: https://stackoverflow.com/questions/34404496/webpack-not-converting-es6-to-es5
I unfortunately don't plan to multi build this library. It should be pretty forward to use webpack+babel to compile all your code including third-party library like Marshal to es5.

**Comment by TrevorBroderick1** [comment]
Thanks for trying to help @marcj , I really do appreciate it.

I don't think this quite applies to me because I'm using Angular 9. It helped me figure out what to google though, and unfortunately it seems it's not possible to have Angular transpile external dependencies, even when using the es5 configuration.

I managed to get babel-cli to convert the files into es5 and dropped that into my node_modules, but I'm still getting the error listed by the original poster. Maybe I'm doing it wrong.

I think I'm out of luck here.

**Comment by jhsuCams** [comment]
+1 for IE11 support! Would love to use this in my project.

**Comment by marcj** [comment]
I've create new Angular 9 project and installed Babel with configuration to automatically compile third-party modules down to ES5. Please see here https://github.com/marcj/angular-marshal-example, the commit with all changes is https://github.com/marcj/angular-marshal-example/commit/d1d54ce02f5adbee8a856cedec9d49d63a8de29b.

**Comment by TrevorBroderick1** [comment]
That is way more configuration than I could have imagined. Thank you for showing that it is possible!

**Comment by marcj** [comment]
That's all you'll get and the burden you pay for supporting an very old technologie since I won't publish Marshal. Sorry that's not worth it for me.
