### ISSUE TITLE
ReferenceError: Can't find variable: global ./node_modules/buffer/index.

### ISSUE THREAD

**Issue by pixelone** [marcj/marshal.ts#26]
I am not sure if this is a bug or maybe I missed something on the install. 

I am testing this as a replacement to typestack/class-transformer.  When using marshal.ts in an Ionic 5 Angular application I am getting. 

> Error: Uncaught (in promise): ReferenceError: Can't find variable: global ./node_modules/buffer/index.

```
const serviceData = await this.dataService.getUserOptions();
const results = plainToClass(UserOptions, serviceData);
console.log(results);
```
If I swap the plainToClass back to typestack/class-transformer I don't get this error. 

```
   Ionic CLI                     : 6.3.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0
```
Possibly related to this?  https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

**Comment by marcj** [comment]
Put `(window as any).global = window;` in your `main.ts` and try again.

**Comment by pixelone** [comment]
Thanks that resolved it.  

By default typestack/class-transformer plainToClass on an array of objects work fine.  When I try swapping the import back to marshal.ts plaintToClass I get

`Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.`

Is this something I am doing wrong or does it just not work on arrays?

Overall this seems like a nice replacement just trying to grasp some basic usage.  

Thanks again.

**Comment by marcj** [comment]
plainToClass only supports objects. You should use `map` for this use case.

```typescript
@Component({
     template: `
      <ng-container ngFor="let item of items">
     </ng-container>
    `
})
class MyClass {
    public items: any[];

   ngOnInit() {
       const myData = [...., ....];
       this.items = myData.map(v => plainToClass(MyDataType, v);
   } 
}
```

Also never use in ngFor objects that are created all the time, as this would lead to render/layout trashing.

**Comment by marcj** [comment]
I'm going to close this since `buffer` is not used anymore in Marshal. It is using now the native available ArrayBuffer or typed arrays.
