### ISSUE TITLE
Feature: Option to keep fields that is not marked with decorators

### ISSUE THREAD

**Issue by eMuonTau** [marcj/marshal.ts#27]
class-transformer is keeping unknown fields by default and it has an option to disable this behavior. Is it possible to implement something similar?
https://github.com/typestack/class-transformer#enforcing-type-safe-instance

**Comment by marcj** [comment]
This is by design not possible, also because it would be a security risk. I'd recommend you to add dynamic fields into a map field

```
class MyType {

     @f.any().asMap()
     dynamicFields: {[name: string]: any} = {};
} 

```

**Comment by eMuonTau** [comment]
Thanks for quick reply. I agree that default behavior is secure. But an option for keeping extra fields would be awesome.

**Comment by marcj** [comment]
No problem. Unfortunately, that's not possible and would decrease performance. I recommend you to not do thi, if not possible work around it by using any type.
