### ISSUE TITLE
More strict handling of Date object

### ISSUE THREAD

**Issue by Bnaya** [marcj/marshal.ts#3]
```
  @Field(Date)
  public end_time: Date;
```
When i'm passing `"start_time": "",`
I get no validation error, but `null`. same for when passing blah string.
When passing number.
Is there a way to make it accept only JSONed date objects?

**Comment by marcj** [comment]
plainToClass does not validate per default. You should use [validate](https://marshal.marcj.dev/modules/_marcj_marshal.html#validate) before you pass the data into `plainToClass`

```typescript
class Entity {
  @Field(Date)
  public end_time: Date;
}
const data = {end_time: ""};
const errors = validate(Entity, data);
if (errors.length) {
    //handle it
}
const entity = plainToClass(Entity, data);
```

I just pushed a new method [validatedPlainToClass](https://github.com/marcj/marshal.ts/commit/cb19eb738dbbd4bd946756ab192e61801a467ce2#diff-be4ffc256db5e06102db2908d9231a2aR633) which does both at the same time. It throws ValidationFailed exception when validation failed.

```
await validatedPlainToClass(Entity, data);
```

I also added more [Date validations](https://github.com/marcj/marshal.ts/commit/cb19eb738dbbd4bd946756ab192e61801a467ce2#diff-e598d5fc2fcd6c11069d74609e59c588R109), they were basically non-existent. Thanks for pointing out! Let me know if that fixes for you.

**Comment by marcj** [comment]
I also removed the async nature of validation, as there was basically no need for t.

**Comment by marcj** [comment]
Released in `v0.8.0`.

**Comment by Bnaya** [comment]
I'm actually using the Marshal ValidationPipe and had this problem there

**Comment by marcj** [comment]
I see, should be fixed now =)

**Comment by Bnaya** [comment]
Thank you very much!
