### ISSUE TITLE
Cross field validation

### ISSUE THREAD

**Issue by alex6o** [marcj/marshal.ts#31]
First of all I want to congratulate to this awesome lib! The integration was easy due to the documentation 👍
I started to implement some custom validation for specific fields, but I have a use case where the validation logic depends on the data of other fields. Is it somehow possible to access these other fields to implement cross field validation?

**Comment by marcj** [comment]
That's not possible. You should create your own function wrapper around it and do the validation there for now.

**Comment by alex6o** [comment]
Ok thank you very much for the fast feedback!
