### ISSUE TITLE
Type mismatch error with arrays

### ISSUE THREAD

**Issue by lcabyss** [marcj/marshal.ts#33]
Using the example code provided, I'm getting the following error:

decorators.js:1749 Uncaught Error: SimpleModel::tags type mismatch. Given String[], but declared is undefined. Please use the correct type in @f.type(T).
    at eval (decorators.js:1749)
    at fn (decorators.js:1421)

I have modified my tsconfig.json to enable experimentalDecorators and emitDecoratorMetadata

{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
...
   }
}

I have installed the reflect-metadata package as well and importing it with the example code.

Removing any array decorators, it runs successfully, but the array properties are not populated obviously.

Example code:

import {
    f,
    plainToClass,
    uuid,
} from '@marcj/marshal';
import 'reflect-metadata';

class SubModel {
    @f label: string;
}

export enum Plan {
    DEFAULT,
    PRO,
    ENTERPRISE,
}

class SimpleModel {
    @f.primary().uuid()
    id: string = uuid();

    @f.array(String)
    tags: string[] = [];

    @f.optional() //binary
    picture?: ArrayBuffer;

    @f
    type: number = 0;

    @f.enum(Plan, /*allowLabelsAsValue=*/ true)
    plan: Plan = Plan.DEFAULT;

    @f
    created: Date = new Date;

    @f.array(SubModel)
    children: SubModel[] = [];

    @f.map(SubModel)
    childrenMap: {[key: string]: SubModel} = {};

    constructor(
        @f.index().asName('name') //asName is required for minimized code
        public name: string
    ) {}
}

//data comes usually from files or http request
const instance = plainToClass(SimpleModel, {
    name: 'myName',
    tags: ['foo', 'bar'],
    plan: 'PRO',
    created: 'Sat Oct 13 2018 14:17:35 GMT+0200',
    children: [{label: 'foo'}],
    childrenMap: {'foo': {label: 'foo'}},
});
console.log(instance);

**Comment by lovespreader** [comment]
Hi,

I just had the same issue and it was provoked by Babel which prevents metadata from being emitted (see [https://github.com/babel/babel/issues/9681](url)).

If you do use Babel and as stated in the issue linked, you can install the following plugin: [https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata#readme](url). It did solve my issue!

**Comment by lcabyss** [comment]
That was it! I knew I was missing something. Thank you very much for the reply!
