### ISSUE TITLE
Compare performance with jackson-js?

### ISSUE THREAD

**Issue by maleet** [marcj/marshal.ts#34]
class-transformer looks dead. Maybe you could compare with 
https://github.com/pichillilorenzo/jackson-js
This lib also supports class polymorphism, would be nice to see performance difference

**Comment by marcj** [comment]
You can easily create a benchmark. But as long as you don't have a JIT engine, Marshal will always be order of magnitudes faster.

**Comment by maleet** [comment]
Manage to test it. Jackson-js is really slow. Count of 100 000 was to much for it... that bad
