### ISSUE TITLE
Cannot access 'class' before initialization

### ISSUE THREAD

**Issue by rodp82** [marcj/marshal.ts#35]
Hi, 

Given the following scenario:
```typescript
class Parent {
  @f
  name: string;

  @f.array(Child)
  children: Child[];
}

class Child {
  @f
  name: string;

  @f.type(Parent)
  parent: Parent;
}
```

How do you get around the issue of using a class before its declared?
I'm using this with angular 8
Thanks

**Comment by marcj** [comment]
You work around those issues by splitting parent child up in 2 different files and then use `@.forward(() => Parent)`
