### ISSUE TITLE
Serialize Class from an external module 

### ISSUE THREAD

**Issue by PetterGs** [marcj/marshal.ts#36]
What would be the best way to serialize a Class imported from an external module 'library'. BabylonJS for instance.

Would it be possible to create a custom function that creates a new Class instance on deserialization.

**Comment by marcj** [comment]
This feature is now implemented and will be released shortly. https://github.com/marcj/marshal.ts/commit/dadf0ec3a6567f8a211cb1041e895af966e4c0b2
