### ISSUE TITLE
[Suggestion / Request] Add validation error code mechanism, and or I18n 

### ISSUE THREAD

**Issue by Bnaya** [marcj/marshal.ts#4]
In many cases, the client needs to "understand" the error, and not only use the error string as is.

Use cases: show specific ui for specific errors.
i18n the errors on client side.

**Comment by marcj** [comment]
Yeah I agree, good idea. 👍

**Comment by marcj** [comment]
Added in https://github.com/marcj/marshal.ts/commit/b5325f23a6c517100b421b14fb80cfe6a0aae51b

**Comment by marcj** [comment]
Released in `v0.8.0`.
