### ISSUE TITLE
example of partialPlainToMongo

### ISSUE THREAD

**Issue by euphario** [marcj/marshal.ts#40]
Hello,

I am trying to understand how to use the partials, especially in the context of Mongo. Could you provide a quick example of making a partial update of a document in Mongo? There must be something simple that I missing but I am struggling. I got plainToClass to work just fine, they return class instance, but partialPlainToClass returns an object not an instance of a class. And I am failing to understand how to make use of it to update specific fields in a Mongo document.

Thank you

**Comment by marcj** [comment]
Depends on how you manage Mongo. If you use the Mongo client directly, you can just use `updateOne`.

```typescript
const patches = {
    'fieldA': 'abcd',
    'deep.foo': '123',
};

const mongoFilter = {
    id: 12,
};

const update = {
    '$set': partialClassToMongo(ClassType, patches),
}
aawait collection.updateOne(mongoFilter, updateStatement);
```

alternatively with `marshal-mongo` package.


```typescript
import {Database, Connection} from "@marcj/marshal-mongo";

const  database = new Database(new Connection('localhost', 'testing');

await database.query(ClassType).filter({id: 12}).patchOne({
    'fieldA': 'abcd',
    'deep.foo': '123',
});
```

**Comment by euphario** [comment]
Absolutely perfect. I had not noticed patchOne.
Thank you very much, and great work on the library, very much enjoying working with it.
