### ISSUE TITLE
Enums are broken in webpack builds > 2.1.3

### ISSUE THREAD

**Issue by hilkeheremans** [marcj/marshal.ts#42]
Hey there,

I recently upgraded to one of the last versions you published (2.1.5). On the face of it, in a classic tsc build, everything works fine. However, when I run a webpack build (e.g. for my serverless deploys), my classes annotated with a classic enum throw the following error on startup:
```
Error: GJOriginConfig::logo type mismatch. Given Object, but declared is Object or undefined. The actual type is an Object, but you specified a Class in @f.type(T).
Please declare a type or use @f.map(Object) for 'logo: {[k: string]: Object}'.
```
Reverted to 2.1.3, and all is well. I annotate them as you usually would with marshal.ts, nothing fancy going on.

I'm woefully short on time but will try to set up a repo with a repro for this, unless you already have an idea of what might be going on. Please let me know!

**Comment by hilkeheremans** [comment]
Also, keep up the great work!

**Comment by marcj** [comment]
Thanks for the report. Could you post your code causing this error?

**Comment by hilkeheremans** [comment]
Due to confidentiality, no, but give me a few days to find some time and I will try to create a simplified code example..

**Comment by marcj** [comment]
Would be enough to post the enum and the property definition that uses it.

**Comment by marcj** [comment]
Also when this error is thrown, there's is something written to the console.log logs, which starts with `type`. Please post that log as well.

**Comment by hilkeheremans** [comment]
I hadn't managed to get to getting back to you until now, sorry! 

Just wanted to let you know I noticed your commit which triggered me to test this again. The webpack compile with the same code is now successful.

--> issue fixed as far as I'm concerned, at least as soon as you release. Thanks!

**Comment by marcj** [comment]
nice! how did you test the not released Marshal?
