### ISSUE TITLE
Custom Property Validator Classes fail in minimized (not uglified) webpack builds

### ISSUE THREAD

**Issue by hilkeheremans** [marcj/marshal.ts#46]
Hi Marc,

Found another nice one. When using Webpack with Terser (mangling disabled), custom validator classes will throw the following error:
```
Class constructor  cannot be invoked without 'new'
```
**Cause:** the Terser plugin compacts those classes into `class{...`, which causes the `isClass` check in `core.ts` to provide a false negative, since that particular function checks for `class` with an extra trailing space. That trailing space is missing in minified webpack builds.

I'll test a fix and submit a PR to this repo and `estdlib.ts` shortly.

**Comment by hilkeheremans** [comment]
I added a PR to `estdlib.ts` here: https://github.com/marcj/estdlib.ts/pull/2

Since a fix requires a version bump and dep update in this repo, it doesn't make sense for me to submit a PR here. :-)

**Comment by marcj** [comment]
Good catch @hilkeheremans! I fixed in master. After working on more features later I will release this asap.
