### ISSUE TITLE
Problem when use validatedPlainToClass with getter in object structure

### ISSUE THREAD

**Issue by rczupa** [marcj/marshal.ts#47]
Hi Marc, how are you ?

We are using this awesome lib!
I have a problem, when we have a class that contains getters, and this getters had in your function some algorithms that use other properties that can be undefined, the process "validatedPlainToClass" fails with the error message:

"Sum constructor is not callable without values. Make sure not to depend on constructor arguments. This is necessary for default value checking."

The code that we are using is:

```
class MonthYearClass {
        @f
        transDate!: Date;

        @f.type(Number)
        get month(): number {
          return this.transDate.getMonth();
        }

        @f.type(Number)
        get year(): number {
          return this.transDate.getFullYear();
        }
      }

      const jun = new Date(2020, 7, 1);

      const testObj = validatedPlainToClass(MonthYearClass, {
        numberOne: 50,
        numberTwo: 123,
        transDate: jun,
      });

      console.log(testObj instanceof MonthYearClass);
      console.log(testObj.month === jun.getMonth());
      console.log(testObj.year === jun.getFullYear());
```
Any suggestions about how can I solve this issue ?

Thanks a lot

**Comment by marcj** [comment]
Yes, you shouldn't decorate the getters. Just use

```
class MonthYearClass {
        @f
        transDate!: Date;

        get month(): number {
          return this.transDate.getMonth();
        }

        get year(): number {
          return this.transDate.getFullYear();
        }
      }
```

You have anything you want already in `transDate`, so there is no need in additionally serialize `month` and `year`.

**Comment by marcj** [comment]
Also you have here a data consistency error, and you forced to ignore it using `!` which is what ultimately is the cause of your problem. With you current class you get also errors using it like this:

```typescript
const instance = new MonthYearClass();
instance.month() //error
```

That's because your `transDate` is empty and you never force the user to set it. In strict mode this wouldn't compile unless you force ignore this issue by using `!` which is bad practise. Instead do it like this:

```typescript
class MonthYearClass {
        @f
        transDate: Date = new Date; //putting a default makes sure all getters work

       //your getters here...
}
```

or force the user to provide it via 

```typescript
class MonthYearClass {
       constructor(@f public transDate: Date) {
       }

       //your getters here...
}
```

**Comment by rczupa** [comment]
Greetings Marc,

Man, thank you so much about your explanations. Now I know how to design correctly the classes and work fine in my project.

Im new in Javascript and typescript, im from Java, and some characteristics im learning at this moment.

Tks so much.
